### ISSUE TITLE
【已知问题】文档页面底部的“编辑页面”指向了不正确的项目

### ISSUE THREAD

**Issue by ghost** [mx-space/docs-archived#15]
如图所示
![image](https://user-images.githubusercontent.com/17929366/166105924-9ab86ed0-aa55-409d-bdc9-9b006d824394.png)

**Comment by ttimochan** [comment]
你提到的问题，我看了一下，确实是这个样子，但不清楚有什么具体的解决办法。（那个设置项似乎无效化了）

**Comment by ghost** [comment]
> 你提到的问题，我看了一下，确实是这个样子，但不清楚有什么具体的解决办法。（那个设置项似乎无效化了）

~~@ttimochan 要不挂个 `help wanted` 吧~~（~~虽然我不觉得会有人在看到这个 issues 后给出 PR 来解决此问题~~
~~还有这个问题我前两天就在群里提过了，Wibus 也没办法~~

直接关啦？那我也关 issues 了（

**Comment by ttimochan** [comment]
已经解决！
