### ISSUE TITLE
文档中静态资源库国内无法正常使用

### ISSUE THREAD

**Issue by 52Lxcloud** [mx-space/docs-archived#38]
## 问题
文档中cdn.jsdelivr.net在国内全部被墙，可以更换为fastly.jsdelivr.net曲线救国

**Comment by ttimochan** [comment]
但是很明显，你提到的也只是临时方案，jsd全线不可用是迟早的事情

**Comment by 52Lxcloud** [comment]
是的，现在也只能抱着能用一时是一时的心态

**Comment by ttimochan** [comment]
好，我去更换
