### ISSUE TITLE
pnpm build构建错误

### ISSUE THREAD

**Issue by arleycn** [mx-space/docs-archived#8]
```
[root@VM-8-10-centos kami]# pnpm build

> mx-kami@3.6.0-alpha.0 build /root/mx-space/kami
> cross-env NODE_ENV=production next build

info  - Loaded env from /root/mx-space/kami/.env
warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
info  - Checking validity of types  
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: /root/mx-space/kami/node_modules/.pnpm/next-pwa@5.4.7_next@12.1.0/node_modules/next-pwa/register.js
> [PWA] Service worker: /root/mx-space/kami/public/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Compile server
info  - Using external babel configuration from /root/mx-space/kami/.babelrc
info  - Attempted to load @next/swc-linux-x64-gnu, but an error occurred: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/mx-space/kami/node_modules/.pnpm/@next+swc-linux-x64-gnu@12.1.0/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node)
info  - Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
info  - Attempted to load @next/swc-linux-x64-musl, but an error occurred: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
error - Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
info  - Creating an optimized production build . ELIFECYCLE  Command failed with exit code 1.

```

服务器：腾讯轻量应用
CentOS 7.9.2009 x86_64(Py3.7.9)
后端正常
[https://github.com/vercel/next.js/discussions/30468](https://github.com/vercel/next.js/discussions/30468)
在项目根目录添加 `.babelrc` 无效
待解决~

**Comment by wibus-wee** [comment]
请阅读文档的系统要求，升级内核

**Comment by ttimochan** [comment]
请认真参阅文档，文档详细的说明了内核要求，至于内核如何升级，如果你不熟悉的话，建议直接ubuntu，kami使用了swc打包，需要较高版本内核的一个扩展。

**Comment by Innei** [comment]
> ```
> [root@VM-8-10-centos kami]# pnpm build
> 
> > mx-kami@3.6.0-alpha.0 build /root/mx-space/kami
> > cross-env NODE_ENV=production next build
> 
> info  - Loaded env from /root/mx-space/kami/.env
> warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
> info  - Checking validity of types  
> info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
> > [PWA] Compile client (static)
> > [PWA] Auto register service worker with: /root/mx-space/kami/node_modules/.pnpm/next-pwa@5.4.7_next@12.1.0/node_modules/next-pwa/register.js
> > [PWA] Service worker: /root/mx-space/kami/public/sw.js
> > [PWA]   url: /sw.js
> > [PWA]   scope: /
> > [PWA] Compile server
> info  - Using external babel configuration from /root/mx-space/kami/.babelrc
> info  - Attempted to load @next/swc-linux-x64-gnu, but an error occurred: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/mx-space/kami/node_modules/.pnpm/@next+swc-linux-x64-gnu@12.1.0/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node)
> info  - Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
> info  - Attempted to load @next/swc-linux-x64-musl, but an error occurred: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
> error - Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
> info  - Creating an optimized production build . ELIFECYCLE  Command failed with exit code 1.
> ```
> 
> 服务器：腾讯轻量应用 CentOS 7.9.2009 x86_64(Py3.7.9) 后端正常 [vercel/next.js#30468](https://github.com/vercel/next.js/discussions/30468) 在项目根目录添加 `.babelrc` 无效 待解决~

nextjs 已经烂到了极致，将就用一下吧。改不了的

**Comment by ghost** [comment]
总结一下三位大佬的发言：由于 nextjs 的稀烂，要不换系统，要不升内核，不然就没法编译。 @arleycn
