### ISSUE TITLE
refactor : rewrite document

### ISSUE THREAD

**Issue by ttimochan** [mx-space/docs-archived#83]
个人觉得目前的文档不够好，近期准备重写

**Comment by miaoermua** [comment]
快写，我 PR

**Comment by wuhang2003** [comment]
快写，~~我也来水 PR~~

**Comment by ttimochan** [comment]
https://github.com/ttimochan/mx-docs/tree/refactor/rewrite


https://github.com/ttimochan/mx-docs/issues/1

**Comment by ttimochan** [comment]
> 快写，我 PR

GKD

**Comment by ttimochan** [comment]
TODO list:
1. [x] 原版安装内容迁移
2. [ ] help 重写
3. [x] 文档对 Windows 系统的支持

**Comment by wibus-wee** [comment]
直接地对 Windows 支持是不可能的，首先 core 里面就已经有很多代码有可能会出现不兼容情况。

~~当然你说docker那当我没说过~~

**Comment by ttimochan** [comment]
> 直接地对 Windows 支持是不可能的，首先 core 里面就已经有很多代码有可能会出现不兼容情况。
> 
> ~当然你说docker那当我没说过~

先试试，不行了就跑路

**Comment by miaoermua** [comment]
> > 直接地对 Windows 支持是不可能的，首先 core 里面就已经有很多代码有可能会出现不兼容情况。
> > 
> > ~当然你说docker那当我没说过~
> 
> 先试试，不行了就跑路

run 就对了(

**Comment by wuhang2003** [comment]
> > > 直接地对 Windows 支持是不可能的，首先 core 里面就已经有很多代码有可能会出现不兼容情况。
> > > ~当然你说docker那当我没说过~
> > 
> > 
> > 先试试，不行了就跑路
> 
> run 就对了(

~~run，都可以 run（无端~~

**Comment by wibus-wee** [comment]
可以看看备份和恢复功能能不能跑，或许要做的事情要比一般要多

**Comment by ttimochan** [comment]
> 可以看看备份和恢复功能能不能跑，或许要做的事情要比一般要多

Yes ， 还需要准备 make 环境，不像 Linux 下 包管理器直接装 make 那么方便

**Comment by ttimochan** [comment]
> 可以看看备份和恢复功能能不能跑，或许要做的事情要比一般要多

Done
