### ISSUE TITLE
文档里的 GitHub 镜像站又双叒叕得换了

### ISSUE THREAD

**Issue by wuhang2003** [mx-space/docs-archived#96]
## 问题
原文档中提到的 `hub.0z.gs` 镜像站已于9月21日下线

## 详细描述
![图片](https://user-images.githubusercontent.com/108316419/192662782-097b0cdf-87e2-45c4-80fb-383cb49511de.png)

**Comment by ttimochan** [comment]
Done

**Comment by wuhang2003** [comment]
> Done

LGTM
